env: ocean

env_args:
  map_name: ocean_hard
  n_types: 2
  num_P: 6
  num_A: 4
  dim: 20
  vision: 2
  tensor_obs: False
  episode_limit: 200
  mode: cooperative
  no_stay: False
  reward_type: 3
  max_wind_speed: ~
  render_save: False
  log_dir: ~
  logis_init_position_over_the_space: True
  scenario_difficulty: hard
  intensity_levels: 4
  num_dest: 1

test_greedy: True
test_nepisode: 50
test_interval: 200000
log_interval: 10000
runner_log_interval: 100000
learner_log_interval: 10000


# t_max: 5050000
t_max: 120050000
training_episodes: 6000



